--- #YAML:1.0
name:                Scalar-Util-Refcount
version:             1.0.2
abstract:            Show an object's reference count.
license:             bsd
author:              
    - Jeremy Nixon <jnixon@cpan.org>
distribution_type:   module
requires:
    perl:            5.008
    Exporter:        5.57
    XSLoader:        0
build_requires:
    Test::More:      0
configure_requires:
    ExtUtils::MakeMaker:    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
